name: CI/CD Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Login en DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir la imagen del backend
        run: |
          docker build -t leonareq/examen-back .
          docker tag leonareq/examen-back leonareq/examen-back:latest

      - name: Subir la imagen a DockerHub
        run: docker push leonareq/examen-back:latest
